services:
  - type: web
    name: flowchart-platform
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
